spring.application.name=twitter

spring.datasource.url=jdbc:postgresql://localhost:5432/twitter_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresSQLDialect

server.port=8085
jwt.secret=sunilbhaikaagekoikuchbolsaktahaikya7999
jwt.expiration=3600000